# Site configuration for the Congo demo site
# --------------------------------------------------------------------------
# IMPORTANT: You should not use this file as a template for configuration
# as it does not contain all the required theme settings!
#
# Refer to the theme docs for configuration instructions if you're unsure.
# https://jpanther.github.io/congo/docs/
# --------------------------------------------------------------------------

theme = "dark-kitten"
languageCode = "en-AU"
defaultContentLanguage = "en"
title = "dark-kitten"
enableEmoji = true
summaryLength = 0

[author]
  name = "dark-kitten"
  image = "img/author.jpg"
  keywords = ["Dark", "Cute", "Dracula"]
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { type = "twitter", link = "https://twitter.com/", desc = "αβγω" },
    { type = "facebook", link = "https://facebook.com/" },
    { type = "linkedin", link = "https://linkedin.com/" },
    { type = "youtube", link = "https://youtube.com/" },
  ]

[taxonomies]
  tag = "tags"

[params]
  colorScheme = "dracula"
  # logo = "logo.jpg"

[params.homepage]
  layout = "profile"
  showRecent = false
  # mainSections = ["samples"]

[params.list]
  groupByYear = false
  showBreadcrumbs = true

[params.article]
  showBreadcrumbs = true
  showEdit = true
  editURL = "https://github.com/jpanther/congo/tree/dev/exampleSite/content/"
  editAppendPath = true

[[menu.main]]
  name = "Docs"
  pageRef = "docs"
  weight = 10
[[menu.main]]
  name = "Samples"
  pageRef = "samples"
  weight = 20
[[menu.main]]
  name = "Users"
  pageRef = "users"
  weight = 30
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/jpanther/congo"
  weight = 40

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
